### ISSUE TITLE
questions about ekf parameters

### ISSUE THREAD

**Issue by softdream** [mrsp/imu_ekf#2]
Hi Stelios,
Thanks for your great contribution.
I noticed there was a function named loadIMUEKFparams() in the file imu_estimator.cpp. I have some questions about what should these parameters be set to. Could you please provide more details about how to set these parameters about the ekf correctly ?
Looking forward for your reply.
Thanks in advance.
Daofeng Du

**Comment by mrsp** [comment]
Hello Daofeng

Unfortunately, this repo is not supported anymore I'll kindly refer you to serow (https://github.com/mrsp/serow) it uses the same floating base estimator with an EKF and IMU/odometry measurements. I've also listed some papers that you could look at.

Parameters are tuned in the corresponding robotic platform files e.g. (https://github.com/mrsp/serow/blob/master/config/estimation_params_cogimon.yaml)

Stelios

**Comment by softdream** [comment]
Hi Stelios,
   Thanks for your detailed information.
   I am making a slam robot without using ros and I need an accurate enough odometer data.I think your work helped me a lot.Thanks again for your code.
   Daofeng Du.

**Comment by mrsp** [comment]
Hi Daofeng

If you are interested in the code kindly see the devel branch of serow it has been recently updated but not yet merged to the master branch. I also recall fixing something the IMUEKF implementation.

https://github.com/mrsp/serow/blob/devel/src/IMUEKF.cpp
