### ISSUE TITLE
Why IMU Initial Biases biasAZ give -20.0327 in the config file?

### ISSUE THREAD

**Issue by bryantaoli** [mrsp/imu_ekf#4]
![image](https://user-images.githubusercontent.com/30526360/77240792-10394580-6c25-11ea-81f3-4b66cd32256e.png)

**Comment by mrsp** [comment]
Hello 

This repo is currently not updated kindly visit [https://github.com/mrsp/serow](https://github.com/mrsp/serow)  the latest stable imu_ekf module is encapsulated in it.

If you provide more information on which application you are planning to use the imu_ekf I can update it.

**Comment by bryantaoli** [comment]
> Hello
> 
> This repo is currently not updated kindly visit https://github.com/mrsp/serow the latest stable imu_ekf module is encapsulated in it.
> 
> If you provide more information on which application you are planning to use the imu_ekf I can update it.

The code in this repo is enough for me, I just want to merge the IMU and the visual odometer. But I have some problems. One of the questions I have raised above,  Another problem is I cannot find the extrinsic parameters of IMU and visual odometers.

**Comment by mrsp** [comment]
Then take the IMUEKF class from https://github.com/mrsp/serow/blob/master/src/IMUinEKF.cpp 
and see how it is initialized in https://github.com/mrsp/serow/blob/master/src/humanoid_ekf.cpp

extrinsic of IMU and Camera can be found with https://github.com/ethz-asl/kalibr

**Comment by bryantaoli** [comment]
> Then take the IMUEKF class from https://github.com/mrsp/serow/blob/master/src/IMUinEKF.cpp
> and see how it is initialized in https://github.com/mrsp/serow/blob/master/src/humanoid_ekf.cpp
> 
> extrinsic of IMU and Camera can be found with https://github.com/ethz-asl/kalibr

I see https://github.com/mrsp/serow/blob/master/src/IMUinEKF.cpp and https://github.com/mrsp/serow/blob/master/src/humanoid_ekf.cpp, and it is better and more complicated than this repo.
And what I want to ask is when I get the extrinsic parameter of IMU and Camera with https://github.com/ethz-asl/kalibr, where should I  put the extrinsic parameter into the code?

**Comment by mrsp** [comment]
Hello! 

I've updated the repo with the following:

i) Fixed minor bugs in the IMUEKF class
ii) Added Self Calibration option for the IMU-biases
iii) Added the TF from IMU to the Base frame to be estimated.
iv) Added Explanatory comments in the IMU EKF class for your convenience.

More information regarding the EKF can be found in my relevant publication, although the title says humanoids, I've written the maths to be generic!

https://www.researchgate.net/publication/334745931_Outlier-Robust_State_Estimation_for_Humanoid_Robots



Let me know if it works for you now.
